### ISSUE TITLE
[IDEA] Add shortcut to remove all trailing spaces in an assembler file

### ISSUE THREAD

**Issue by CoderCoco** [dkelosky/vscode-ibm-hlasm#4]
Typically when working with an assembler file, there are times where I am reordering code leaving endless spaces at the end of my assembler lines. When it comes time to upload, I get many errors indicating that I've exceeded the LRECL for the remote data set due to trailing spaces in the file.

It might be a good idea to add a shortcut command that trims all trailing spaces from an assembler file.

**Comment by spgennard** [comment]
Can you use the editor setting "files.trimTrailingWhitespace": true ?

**Comment by dkelosky** [comment]
Good point @spgennard - @CoderCoco - does that work for you?

**Comment by mhammack** [comment]
I was thinking the same thing, but there is a user option to remove trailing spaces on “save”.  Turn on the option “Trim Trailing Whitespace” under Text Editor->Files and then save. Viola, whitespace trimmed.

Mark 
(sent from my iPhone)

**Comment by mhammack** [comment]
Yes

Mark 
(sent from my iPhone)

**Comment by dkelosky** [comment]
Thanks, I'll close this in favor of that.

**Comment by CoderCoco** [comment]
Yeah, that works for me @dkelosky
